In [9]:
import numpy as np

arr=np.array([1.2,3.4,5.4,7.5,])
print(arr.dtype)


float64


In [29]:
import numpy as np
arr2=np.zeros((2,3))
print(arr2)
arr1 = np.array([[0,0,0], [0,0,0]])
print(arr1.dtype)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
int32
[[0 0 0]
 [0 0 0]]


In [19]:
tup=([1,2,3],[4,5,6])
print(type(tup))
arr=np.asarray(tup)
print(type(arr))
print(arr)

<class 'tuple'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [17]:

randn = np.random.randint(10,100,(2,3))
print(randn)

[[96 40 19]
 [67 20 13]]
